# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:11.15.0

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - yarn
          - yarn test
  branches:
    master:
      - step:
          deployment: Production-heroku1
          caches:
            - node
          script:
            - yarn
            - yarn build-dev
            - tar czfv application.tgz package.json server.js build/
            - pipe: atlassian/heroku-deploy:1.0.0
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: $HEROKU_APP_NAME
                ZIP_FILE: 'application.tgz'
                WAIT: 'true'
                # DEBUG: '<boolean>' # Optional